version: '3.8'

services:
  whisper-api:
    build: .
    ports:
      - "8000:5000"
    environment:
      - PYTHONPATH=/app
    volumes:
      # Volume para cache do modelo Whisper (opcional, melhora performance)
      - whisper_cache:/root/.cache/whisper
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  whisper_cache: